### ISSUE TITLE
windows run is error

### ISSUE THREAD

**Issue by zanjs** [GetExpert/redux-blog-example#31]
```
E:\zan\www\auth\redux-blog-example>npm start

> @ start E:\zan\www\auth\redux-blog-example
> set NODE_ENV=production babel-node ./api & node . & wait

module.js:339
    throw err;
    ^

Error: Cannot find module 'E:\zan\www\auth\redux-blog-example'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
'wait' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! @ start: `set NODE_ENV=production babel-node ./api & node . & wait`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'set NODE_ENV=production babel-node ./api
& node . & wait'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     set NODE_ENV=production babel-node ./api & node . & wait
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\zan\www\auth\redux-blog-example\npm-debug.log

```

**Comment by lishoulong** [comment]
I also encounter the same problem.
